services:
  frontend:
    build: /mnt/z/DevOpsWithDocker/Part-2/ex_2_3/example-frontend/.
    ports:
      - "5000:5000"
    depends_on:
      - web
  backend:
    build: /mnt/z/DevOpsWithDocker/Part-2/ex_2_3/example-backend/.
    ports:
      - "8080:8080"   
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    depends_on:
      - redis
      - db
      - web
    volumes:
      - /mnt/z/DevOpsWithDocker/Part-2/ex_2_8/database:/var/lib/postgresql/data/:rw
  redis:
    image: redis:latest
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
  web:
    image: nginx
    volumes:
      - /mnt/z/DevOpsWithDocker/Part-2/ex_2_8/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80  
volumes:
  database:
  
  




